### ISSUE TITLE
Has the Terraform dropped out ?

### ISSUE THREAD

**Issue by davegddd** [AppThreat/sast-scan#26]
I seem to be unable to run it.

sast:
  stage: test
  image: 
    name: appthreat/sast-scan
  script:
    - scan --src ${TF_ROOT} --type Terraform --out_dir ${CI_PROJECT_DIR}/reports
  artifacts:
    paths:
      - $CI_PROJECT_DIR/reports/

**Comment by prabhu** [comment]
Hi @davegddd ,

Please use `shiftleft/sast-scan` as the image. It supports more languages and feature rich.

Documentation for GitLab is below.

https://slscan.io/en/latest/integrations/gitlab/

**Comment by davegddd** [comment]
thank you - I just realised it's was the uppercase T of Terraform =. terraform that caused it.
will switch to shift left instead
